'use strict';/*****************************************************//********** Show-hide option modal window ************//*****************************************************/(function(){function showModalOptions(btnClass,modalWindow){$(btnClass).on('click',function(){// Close all modal windows, when opening a new modal window
$('.the-modal').slideUp('fast');if($(modalWindow).is(':hidden')==true){$(modalWindow).slideDown('fast');}else if($(modalWindow).is(':hidden')==false){$(modalWindow).slideUp('fast');}});}// Main menu
showModalOptions('.main-menu-bars','.main-menu__search-and-nav');showModalOptions('.main-menu-cart__content','.opt-cart');showModalOptions('.main-menu-wishlist','.opt-wishlist');showModalOptions('.user-menu__content','.opt-user-menu');// Main menu v4
showModalOptions('.main-menu-v4-cart__content','.opt-cart');showModalOptions('.main-menu-v4-wishlist','.opt-wishlist');// Top line 
showModalOptions('.payment','.opt-payment');showModalOptions('.language','.opt-lang');showModalOptions('.category','.opt-category');// Shop
showModalOptions('.product-item-v2-color','.opt-color');showModalOptions('.product-item-v2-size','.opt-size');showModalOptions('.product-item-v2-type','.opt-type');})();/*****************************************************//********************* Dropdown **********************//*****************************************************/(function(){function addToggleIcon(classIcon){var link=$('.main-menu-navbar__li');link.children('.main-menu-navbar-dropdown').prev().addClass(classIcon);}addToggleIcon('tringle');addToggleIcon('tringleMobile');$('.main-menu-navbar__link').on('click',function(e){var target=e.target;if($(target).parent().find('ul.main-menu-navbar-dropdown').length!==0){e.preventDefault();}});if($(window).width()<992){(function dropDownMenu(){$('.main-menu-navbar__link').on('click',function(e){var target=e.target;if($(target).parent().children('.main-menu-navbar-dropdown').is(':hidden')==true){$(target).parent().children('.main-menu-navbar-dropdown').slideDown('fast');}else if($(target).parent().children('.main-menu-navbar-dropdown').is(':hidden')==false){$(target).parent().children('.main-menu-navbar-dropdown').slideUp('fast');}});})();};})();/*****************************************************//********* Dropdown for Main menu v4 *****************//*****************************************************/(function(){var targetColor=$('.backTop').css('background-color');var link=$('.main-menu-v4-navbar__li');link.children('.main-menu-v4-navbar-dropdown').parent().addClass('afterShow');$('.main-menu-v4-navbar__link').on('click',function(e){var target=e.target;if($(target).parent().find('ul.main-menu-v4-navbar-dropdown').length!==0){e.preventDefault();}});// if ($(window).width() < 992) {
(function dropDownMenu(){$('.main-menu-v4-navbar__link').on('click',function(e){var target=e.target;$('.main-menu-v4-navbar-dropdown').hide('fast');$('.main-menu-v4-navbar__li').removeClass('bgForActive');if($(target).parent().children('.main-menu-v4-navbar-dropdown').is(':hidden')==true){$(target).parent().children('.main-menu-v4-navbar-dropdown').css("display","flex");$(target).parent().addClass('bgForActive');}else if($(target).parent().children('.main-menu-v4-navbar-dropdown').is(':hidden')==false){$(target).parent().removeClass('bgForActive');$(target).parent().children('.main-menu-v4-navbar-dropdown').css("display","none");}});})();// };
})();/*****************************************************//**************** Fixed Main menu ******************//*****************************************************/(function(){if($(window).width()>992){$(".fixed-menu").sticky({zIndex:10});}})();/*****************************************************//********************** Right block ******************//*****************************************************/(function(){function showRightBlock(btnClass,modalWindow){$(btnClass).on('click',function(){if($(modalWindow).hasClass('hideBlock')){$(modalWindow).removeClass('hideBlock');}else{$(modalWindow).addClass('hideBlock');}});}showRightBlock('.show-right-block','.right-block');})();/*****************************************************//********************** Main menu v4 ******************//*****************************************************/(function(){function showRightBlock(btnClass,closeBtn,modalWindow){$(btnClass).on('click',function(){$(modalWindow).addClass('show-Main-menu-v4');});$(closeBtn).on('click',function(){$(modalWindow).removeClass('show-Main-menu-v4');});}showRightBlock('.open-main-menu-v4','.close-main-menu','.main-menu-v4');})();//------------ Search modal window hide -------------------\\
$('.search-modal').hide('fast');var accentColorMap=$('.subscribe__content').css('background-color');//--------------- Google map options ---------------\\
function initMap(){var uluru={lat:40.674,lng:-73.945};// Styles a map in night mode.
var main_color='#0E2646',//Main color
saturation_value=-1,//saturation
brightness_value=1;//brightness
//Style for elements on map
var style=[{//Saturation of notation on the map
elementType:"labels",stylers:[{saturation:saturation_value}]},{//We hide the signs of metro stations, stations, airports and other transport links on the map
featureType:"poi",elementType:"labels",stylers:[{visibility:"off"}]},{//Hide the road designation on the map
featureType:'road.highway',elementType:'labels',stylers:[{visibility:"off"}]},{//Hide the designation of local roads
featureType:"road.local",elementType:"labels.icon",stylers:[{visibility:"off"}]},{//Hide the designation of the highway on the map
featureType:"road.arterial",elementType:"labels.icon",stylers:[{visibility:"off"}]},{//Hide road signs on the map
featureType:"road",elementType:"geometry.stroke",stylers:[{visibility:"off"}]},//Styles for different elements on the map
{featureType:"transit",elementType:"geometry.fill",stylers:[{hue:main_color},{visibility:"on"},{lightness:brightness_value},{saturation:saturation_value}]},{featureType:"poi",elementType:"geometry.fill",stylers:[{hue:main_color},{visibility:"on"},{lightness:brightness_value},{saturation:saturation_value}]},{featureType:"poi.government",elementType:"geometry.fill",stylers:[{hue:main_color},{visibility:"on"},{lightness:brightness_value},{saturation:saturation_value}]},{featureType:"poi.sport_complex",elementType:"geometry.fill",stylers:[{hue:main_color},{visibility:"on"},{lightness:brightness_value},{saturation:saturation_value}]},{featureType:"poi.attraction",elementType:"geometry.fill",stylers:[{hue:main_color},{visibility:"on"},{lightness:brightness_value},{saturation:saturation_value}]},{featureType:"poi.business",elementType:"geometry.fill",stylers:[{hue:main_color},{visibility:"on"},{lightness:brightness_value},{saturation:saturation_value}]},{featureType:"transit",elementType:"geometry.fill",stylers:[{hue:main_color},{visibility:"on"},{lightness:brightness_value},{saturation:saturation_value}]},{featureType:"transit.station",elementType:"geometry.fill",stylers:[{hue:main_color},{visibility:"on"},{lightness:brightness_value},{saturation:saturation_value}]},{featureType:"landscape",stylers:[{hue:main_color},{visibility:"on"},{lightness:brightness_value},{saturation:saturation_value}]},{featureType:"road",elementType:"geometry.fill",stylers:[{hue:main_color},{visibility:"on"},{lightness:brightness_value},{saturation:saturation_value}]},{featureType:"road.highway",elementType:"geometry.fill",stylers:[{hue:main_color},{visibility:"on"},{lightness:brightness_value},{saturation:saturation_value}]},{featureType:"water",elementType:"geometry",stylers:[{hue:main_color},{visibility:"on"},{lightness:brightness_value},{saturation:saturation_value}]}];// Options map
var map=new google.maps.Map(document.getElementById('google-map'),{center:uluru,scrollwheel:false,zoom:15,styles:style});// Set marker on map
var marker=new google.maps.Marker({position:uluru,map:map});}//------------------- Star rating -------------------\\
var starColor=$('.backTop').css('background-color');function starRating(Class){$(Class).rateYo({rating:3.6,starWidth:"20px",normalFill:'#6b6a64',ratedFill:starColor});};starRating(".product-item__rateYo");starRating(".view-detail__rateYo");starRating(".product-item2__rateYo");//--------------- Button back to top ----------------\\
if($('#backTop').length){var scrollTrigger=100,// px
backToTop=function backToTop(){var scrollTop=$(window).scrollTop();if(scrollTop>scrollTrigger){$('#backTop').addClass('show');}else{$('#backTop').removeClass('show');}};backToTop();$(window).on('scroll',function(){backToTop();});$('#backTop').on('click',function(e){e.preventDefault();$('html,body').animate({scrollTop:0},700);});}//----------------Init mixitup grid-----------------\\
var filterList={init:function init(boxClass,itemClass){$(boxClass).mixItUp({selectors:{target:itemClass,filter:'.products-filter__btn'},load:{filter:'.mix'}});}};filterList.init('.products-item','.product-item');//-------------------- FadeIn effect for modal window ------------\\
function showModal(btnClass,modalWindow){$(btnClass).on('click',function(){if($(modalWindow).is(':hidden')==true){$(modalWindow).fadeIn();}else if($(modalWindow).is(':hidden')==false){$(modalWindow).fadeOut();}});}// View detail pruduct modal window
$('.view-detail').hide();showModal('.open-modal-view-detail','.view-detail');showModal('.view-detail__btn-close','.view-detail');// Search modal
showModal('.main-menu-search-btn','.search-modal');showModal('.main-menu-v4-search-btn','.search-modal');showModal('.search-modal__btn-close','.search-modal');// Preloader
setTimeout(function(){$('.preloader').fadeOut("slow",function(){// Animation complete.
});},1000);// Clock
var clock=$('.deal__clock').FlipClock({clockFace:"dailyCounter",autoStart:false,collbacks:{stop:function stop(){$('.deal__clock-message').html('Stop');}}});var finish="November 01 2017 00:00:00";var first=new Date(finish);var last=Date.now();var remaning=(first-last)/1000;clock.setTime(remaning);clock.setCountdown(true);clock.start();// Parallax
function parallaxIt(){var $fwindow=$(window);$('[data-type="content"]').each(function(index,e){var scrollTop=$fwindow.scrollTop();var $contentObj=$(this);$fwindow.on('scroll resize',function(){scrollTop=$fwindow.scrollTop();$contentObj.css('top',$contentObj.height()*index-scrollTop);});});$('[data-type="background"]').each(function(){var $backgroundObj=$(this);$fwindow.on('scroll resize',function(){var yPos=-($fwindow.scrollTop()/$backgroundObj.data('speed'));var coords='50% '+yPos+'px';// Move the background
$backgroundObj.css({backgroundPosition:coords});});});$fwindow.trigger('scroll');};parallaxIt();$(".checkout-accordeon dd").hide().prev().click(function(){$(this).parents(".checkout-accordeon").find("dd").not(this).slideUp().prev().removeClass("active");$(this).next().not(":visible").slideDown().prev().addClass("active");});var aboutSliderOwl=$('.about-slider-carousel').owlCarousel({loop:true,autoplay:true,autoplaySpeed:1000,margin:15,nav:false,smartSpeed:1200,responsive:{0:{items:1},600:{items:2},1000:{items:4}}});$(".about-slider_nav-left").click(function(){aboutSliderOwl.trigger('prev.owl.carousel');});$(".about-slider_nav-right").click(function(){aboutSliderOwl.trigger('next.owl.carousel');});$('.partners-carousel').owlCarousel({loop:true,autoplay:true,autoplaySpeed:1000,margin:15,nav:false,smartSpeed:1200,responsive:{0:{items:2},600:{items:3},1000:{items:4}}});var filterList={init:function init(){$('.blog-list-item').mixItUp({selectors:{target:'.blogItem',filter:'.blog-list-filter__btn'},load:{filter:'.mix'}});}};filterList.init();var recentPostOwl=$('.recent-post__carousel').owlCarousel({loop:true,autoplay:true,autoplaySpeed:1000,margin:30,nav:false,smartSpeed:1200,responsive:{0:{items:1},600:{items:2},1000:{items:3}}});$(".recent-post_nav-left").click(function(){recentPostOwl.trigger('prev.owl.carousel');});$(".recent-post_nav-right").click(function(){recentPostOwl.trigger('next.owl.carousel');});// (function() {
//     let container = $('.collections-list__content');
//     container.imagesLoaded(function() {
//         container.masonry({
//             columnWidth: '.collections-list-item',
//             itemSelector: '.collections-list-item'
//         });
//     });
// })();
jQuery('<div class="quantity-nav"><div class="quantity-button quantity-up">+</div><div class="quantity-button quantity-down">-</div></div>').insertAfter('.product-detail-quantity input');jQuery('.product-detail-quantity').each(function(){var spinner=jQuery(this),input=spinner.find('input[type="number"]'),btnUp=spinner.find('.quantity-up'),btnDown=spinner.find('.quantity-down'),min=input.attr('min'),max=input.attr('max');btnUp.click(function(){var oldValue=parseFloat(input.val());if(oldValue>=max){var newVal=oldValue;}else{var newVal=oldValue+1;}spinner.find("input").val(newVal);spinner.find("input").trigger("change");});btnDown.click(function(){var oldValue=parseFloat(input.val());if(oldValue<=min){var newVal=oldValue;}else{var newVal=oldValue-1;}spinner.find("input").val(newVal);spinner.find("input").trigger("change");});});(function(){var content=$('.product-features-content');for(var i=1;i<content.length;i++){$(content[i]).addClass('disNone');};$('.product-features-tabs').on('click',function(e){var target=e.target;var tabs=$('.product-features-tabs__tab');if($(target).hasClass('product-features-tabs__tab')){for(var _i=0;_i<content.length;_i++){$(content[_i]).addClass('disNone');$(content[_i]).removeClass('disBlock');};for(var _i2=0;_i2<tabs.length;_i2++){$(tabs[_i2]).removeClass('product-features-active');};$(target).addClass('product-features-active');$('.'+$(target).attr('data-tab')).addClass('disBlock');}});})();var productRelatedOwl=$('.product-related-carousel').owlCarousel({loop:true,autoplay:true,autoplaySpeed:1000,margin:15,nav:false,smartSpeed:1200,responsive:{0:{items:1},600:{items:2},1000:{items:3}}});$(".product-related__nav-left").click(function(){productRelatedOwl.trigger('prev.owl.carousel');});$(".product-related__nav-right").click(function(){productRelatedOwl.trigger('next.owl.carousel');});$(function(){$("#slider-price").slider({range:true,min:0,max:1000,values:[150,500],slide:function slide(event,ui){$("#amount").val("$"+ui.values[0]+" - $"+ui.values[1]);}});$("#amount").val("$"+$("#slider-price").slider("values",0)+" - $"+$("#slider-price").slider("values",1));});var blogOwl=$('.blog__carousel').owlCarousel({loop:true,autoplay:true,autoplaySpeed:1000,margin:30,nav:false,smartSpeed:1200,responsive:{0:{items:1},600:{items:2},1000:{items:3}}});$(".blog-nav-left").click(function(){blogOwl.trigger('prev.owl.carousel');});$(".blog-nav-right").click(function(){blogOwl.trigger('next.owl.carousel');});var owl=$('.home-slider__home-carousel');// Carousel initialization
owl.owlCarousel({loop:true,// autoplay: true,
autoplaySpeed:1000,margin:15,nav:false,smartSpeed:1200,responsive:{0:{items:1},600:{items:1},1000:{items:1}}});$(".home-nav-left").click(function(){owl.trigger('prev.owl.carousel');});$(".home-nav-right").click(function(){owl.trigger('next.owl.carousel');});// add animate.css class(es) to the elements to be animated
function setAnimation(_elem,_InOut){// Store all animationend event name in a string.
// cf animate.css documentation
var animationEndEvent='webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend';_elem.each(function(){var $elem=$(this);var $animationType='animated '+$elem.data('animation-'+_InOut);$elem.addClass($animationType).one(animationEndEvent,function(){$elem.removeClass($animationType);// remove animate.css Class at the end of the animations
});});}// Fired before current slide change
owl.on('change.owl.carousel',function(event){var $currentItem=$('.owl-item',owl).eq(event.item.index);var $elemsToanim=$currentItem.find("[data-animation-out]");setAnimation($elemsToanim,'out');});// Fired after current slide has been changed
owl.on('changed.owl.carousel',function(event){var $currentItem=$('.owl-item',owl).eq(event.item.index);var $elemsToanim=$currentItem.find("[data-animation-in]");setAnimation($elemsToanim,'in');});var newItemOwl=$('.new-item-carousel').owlCarousel({loop:true,autoplay:true,autoplaySpeed:1000,margin:15,nav:false,smartSpeed:1200,responsive:{0:{items:1},600:{items:2},1000:{items:3}}});$(".new-item_nav-left").click(function(){newItemOwl.trigger('prev.owl.carousel');});$(".new-item_nav-right").click(function(){newItemOwl.trigger('next.owl.carousel');});